"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function ContextPage() {
  const [file, setFile] = useState<File | null>(null);
  const router = useRouter();
  return <main className="company-shell context-shell">
    <aside className="goals-art company-art"><header><img src="/assets/auth/logo-white.svg" alt="Padiworks" /><button className="help-link"><img src="/assets/auth/help-circle.svg" alt="" />Use help</button></header><div className="company-art__content context-art__content"><h2><span>Now that we’re here</span>Tell us, what brings you here? 😀</h2><div className="context-network" aria-hidden="true"><i className="context-network__main" /><span className="context-network__junction" /><span className="context-network__line context-network__line--left" /><span className="context-network__line context-network__line--middle" /><span className="context-network__line context-network__line--right" /><i className="context-network__doc context-network__doc--left" /><i className="context-network__doc context-network__doc--middle" /><i className="context-network__doc context-network__doc--right" /><img className="context-network__arrow" src="/assets/onboarding-goals-arrow-right.svg" alt="" /><span className="context-network__avatar"><img src="/assets/figma-onboarding/context-avatar.png" alt="" /></span></div></div></aside>
    <section className="company-content"><div className="goals-progress"><b /><b /><b /><b /><i /></div><form className="context-form" onSubmit={(event) => event.preventDefault()}><header><h1>Business Intelligence Gathering</h1><p>To pre-fill your strategy, I&apos;ll need some information about your business. Share what you feel comfortable with — all fields are optional, and I&apos;ll work with whatever you provide.</p></header><div className="context-info"><b>i</b><p>PadiworksAI leverages these information to draft your first execution graph (priorities, objectives, etc). We don&apos;t have access to your files, they stay private to your workspace and can be deleted anytime.</p></div><label>Company website or Linkedin page URL <small>(Optional)</small><span className="url-input"><b>https://</b><input placeholder="Enter a valid link" /></span></label><label>Upload a document <small>(Optional)</small><span className="upload-zone"><input type="file" accept=".pdf,.doc,.docx,.txt" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><b><img src="/assets/figma-controls/context-icon-2.svg" alt="" /></b><span><strong>{file?.name ?? "Upload strategy / business plan, recent OKR document, company handbook"}</strong><em>Supported Format: PDF, DOCX, TXT (10mb max each)</em></span></span></label><label>Additional context <small>(Optional)</small><textarea placeholder="Anything else PadiworksAI should know – recent pivots, top constraints, upcoming initiatives..." /></label><footer><button type="button" className="experience-back" onClick={() => history.back()}>← <span>Back</span></button><span><button type="button" className="context-skip">Skip for now</button><button className="experience-continue" onClick={() => router.push("/onboarding/objective")}>Continue <span>→</span></button></span></footer></form></section>
  </main>;
}
